@SecureNotesWebApi_HostAddress = https://localhost:7042

GET {{SecureNotesWebApi_HostAddress}}/weatherforecast/
Accept: application/json



POST {{SecureNotesWebApi_HostAddress}}/api/userauth/login
Content-Type: application/json

{
  "username": "gabeamv",
  "hashedPassword": "test123"
}

###

POST {{SecureNotesWebApi_HostAddress}}/api/userauth/register
Content-Type: application/json

{
  "username": "gabeamv",
  "password": "test123"
}

###

POST {{SecureNotesWebApi_HostAddress}}/api/userauth/login
Content-Type: application/json

{
  "username": "gabeamv",
  "hashedPassword": "test123"
}



###

POST {{SecureNotesWebApi_HostAddress}}/api/payload/send
Content-Type: application/json

{
  "uuid": "testID",
  "sender": "testSender",
  "recipient": "testRecipient",
  "ciphertext": "testCiphertext",
  "key": "testKey",
  "iv": "testIV",
  "tag": "testTag",
  "format": "testFormat",
  "timestamp": "2025-08-24T17:30:00Z",
  "signature": "testSignature"
}

###
